// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTodo = "todo"

// Todo mapped from table <todo>
type Todo struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID int32  `gorm:"column:user_id;not null" json:"user_id"`
	Todo   string `gorm:"column:todo;not null" json:"todo"`
	IsDone bool   `gorm:"column:is_done;not null" json:"is_done"`
}

// TableName Todo's table name
func (*Todo) TableName() string {
	return TableNameTodo
}
